export const likes = [
  { title: "Wind" },
  { title: "Horses" },
  { title: "Colors" },
    { title: "Bread" },
        { title: "Quilts" },
  { title: "Truth" },
          { title: "Kim Petras" },
  { title: "Fire" },
    { title: "Photos" },
      { title: "Paper" },
  { title: "Stars" },
  { title: "Smoke" },
  { title: "Chocolate" },
  { title: "Trees" },
  { title: "Rivers" },
    { title: "Love" },
  { title: "Tigers" },
  { title: "Sun" },
  { title: "Breath" },
  { title: "Light" },
  { title: "Oceans" },
  { title: "Mountains" },
  { title: "Words" },
  { title: "Textiles" },
  { title: "Tea" },
  { title: "Seasons" },
  { title: "Stickers" },
  { title: "Running" }
];
