export const likes = [
  { title: "Horses" },
  { title: "Wind" },
  { title: "Wolves" },
  { title: "Rivers" },
  { title: "Chocolate" },
  { title: "Stars" },
  { title: "Incense" },
  { title: "Love" },
  { title: "Fire" },
  { title: "Light" },
  { title: "Trees" },
  { title: "Mountains" },
  { title: "Bread" },
  { title: "Honesty" },
  { title: "Spirit" },
  { title: "Running" },
  { title: "The Moon" },
  { title: "Colors" },
  { title: "Textiles" },
  { title: "Stickers" },
  { title: "Bread" },
  { title: "Books" },
  { title: "Paper" },
  { title: "Tea" },
  { title: "Jaguars" },
  { title: "Seasons" }
];
