export const likes = [
  { title: "Wind" },
  { title: "Horses" },
  { title: "Color" },
        { title: "Quilting" },
  { title: "Truth" },
  { title: "Stars" },
  { title: "Fire" },
    { title: "Photo" },
              { title: "Kim Petras" },
      { title: "Paper" },
  { title: "Smoke" },
        { title: "Beads" },
          { title: "Bread" },
            { title: "Water" },
                { title: "Sunrise" },
  { title: "Chocolate" },
  { title: "Trees" },
  { title: "Rivers" },
    { title: "Love" },
  { title: "Tigers" },
    { title: "Tigers Eye" },
  { title: "Sun" },
  { title: "Breath" },
  { title: "Light" },
      { title: "Beads" },
  { title: "Oceans" },
  { title: "Mountains" },
  { title: "Words" },
  { title: "Textiles" },
  { title: "Tea" },
  { title: "Seasons" },
  { title: "Stickers" },
  { title: "Running" }
];
